import pandas as pd
import os
import glob
import sys

configfile: "config/config.yaml"
query_file = config["query_file"]
sample_path = config["sample_path"]
outdir = config["outdir"]
exclude_seqs = config["exclude_seqs"]
metadata = "%smetadata.tsv" %outdir
top_only = config["top_only"]

besthit = ""
if top_only:
	besthit = "-subject_besthit"

query_path = os.path.dirname(query_file)
query_name = os.path.basename(query_file).rstrip(".fasta")

sample_files = glob.glob(pathname = "*.fasta", root_dir = sample_path)
samples = [os.path.basename(fn.rstrip(".fasta")) for fn in sample_files]

blacklist_table = pd.read_csv("config/blacklist.tsv")
blacklist = blacklist_table.loc[:, "sample"].tolist()

samples = [sample for sample in samples if sample not in blacklist]

rule all:
	input:
		"%s/%s_blast.tsv" %(outdir, query_name)

rule init:
	output:
		temp("%s/init.tmp" %outdir)
	shell:
		"mkdir -p %s && touch {output}" %outdir

rule metadata:
	input:
		rules.init.output
	output:
		metadata
	run:
		with open(metadata, "w") as meta_file:
			meta_file.write("sample\n")
			for sample in samples:
				meta_file.write("%s\n" %sample)

include: "rules/blast.smk"
include: "rules/query_sizes.smk"
include: "rules/merge_blast.smk"
